### ISSUE TITLE
CLI-813: Upon using self-update to update to 2.x warn customers that PHP 8.x is required

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1073]
Customers running `acli self-update` on 1.x will have the bad surprise to no longer have ACLI functioning correctly after the update because we require 8.x - We cannot assume they will read the release notes and will inevitably be caught by surprise.

Suggested journey:

* Upon running `self-update`, prompt the user with a question if the version that is detected is 1.x
* Question should be something along the lines of "_You are about to upgrade to Acquia CLI <version>. This version requires PHP 8.0 or above. Do you want to proceed?_"
* If the user answers "yes", then proceed with the update
* If the user answers "no", then do nothing.

**Comment by danepowell** [comment]
I opened an upstream issue, but I think we need to solve this ourselves. Maybe by creating our own update command that extends SelfUpdateCommand and adds custom logic around the 2.x upgrade.

https://github.com/consolidation/self-update/issues/22

**Comment by danepowell** [comment]
@anavarre I started to work on this and realized it's pointless because we have no way to push a 1.x code change to existing customers.

Let's say someone is running ACLI 1.30.1 in a PHP 7.4 environment. Running `self:update` would upgrade them to 2.0.1 and break their install.

We were planning to make this change and presumably cut 1.31.0. But the customer running `self:update` would never see 1.31.0, it would just jump straight to 2.0.1.

This would only help customers that are savvy enough to manually download the 1.31.0 phar but then run `self:update` by accident to upgrade to 2.0.1. That's got to be a very small or non-existent segment.
