### ISSUE TITLE
CLI-865: drush uli doesn't give admin access after a database:pull

### ISSUE THREAD

**Issue by SamFoster** [acquia/cli#1198]
Hi folks

Any idea why I can't access the Drupal GUI as admin if I run 'drush uli' after a database:pull? In fact I have no access to any of the content - even that which is supposed to be for anonymous users!

All looks ok in Drush status etc.

Thanks

**Comment by anavarre** [comment]
Is this happening to you in Cloud IDE? If yes, that's something we're working on fixing as we speak.

**Comment by SamFoster** [comment]
Yes it is happening there - so good to hear -  I thought I was losing my marbles!

Is there a workaround I can follow for now?

Thanks

Sam

________________________________

**Comment by anavarre** [comment]
Your last message hints at something probably different and related to the Drupal application, not Cloud IDE. Drupal fails to bootstrap because of the following error:

```
TypeError: Argument 1 passed to Drupal\moderated_content_bulk_publish\EventSubscriber\HandlerFor403AccessDenied::on403()
```

What's odd is it seems to have been fixed a while ago https://www.drupal.org/project/moderated_content_bulk_publish/issues/3137395

In any case, the issue I was referring to initially is related to DBs that are automatically created in Cloud IDE. Due to a missed requirement they are only accessible by the MySQL `root` user while they should also be accessible by the `drupal` user.

**Comment by SamFoster** [comment]
OK, thanks for that clarification, that's very kind of you and I appreciate your reply. Thank you. I will keep my eye on the original issue I reported. Thanks again,

Sam

Thanks,

Sam

Sam Foster
Bangor University
________________________________

**Comment by anavarre** [comment]
Cool stuff. Since there's no work to do for Acquia CLI I'm closing this out. If you encounter any issue you know where to find us 😉

**Comment by SamFoster** [comment]
Sorry - so the original issue re the access after a db pull is now fixed is it?

Sam
________________________________

**Comment by anavarre** [comment]
The issue with the DB permissions is not one Acquia CLI can fix. We will release a new version of Cloud IDE next week with the hotfix and will publish release notes at https://docs.acquia.com/ide/release-notes/ as usual.

**Comment by SamFoster** [comment]
Thanks for that. Is there a Github ticket that relates to this database issue that I can view/review and keep track of?

Thanks again,

Sam

Thanks,

Sam

Sam Foster
Bangor University
________________________________

**Comment by anavarre** [comment]
Unfortunately no. Cloud IDE is not a public repo.
