### ISSUE TITLE
CLI-962: Getting exception while running "acli cs:wizard" command

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1377]
Getting below exception while running `acli cs:wizard` command in cloud ide

```
In ExceptionThrower.php line 71:
                     
  avatar is invalid  
                     

codestudio:wizard [--key KEY] [--secret SECRET] [--gitlab-token GITLAB-TOKEN] [--gitlab-project-id GITLAB-PROJECT-ID] [--gitlab-host-name GITLAB-HOST-NAME] [--] [<applicationUuid>]
```

**Comment by anavarre** [comment]
FYI Cloud UI just removed the avatar from "users" in accounts.acquia.com - I think that's why it's happening.

**Comment by joshirohit100** [comment]
Do we have any workaround for this?

**Comment by anavarre** [comment]
Remove the avatar and try again? @danepowell thoughts?

**Comment by danepowell** [comment]
As near as I can tell, ACLI is doing nothing wrong here. The problem seems to lie in the upstream GitLab client: https://github.com/GitLabPHP/Client/issues/739

ACLI correctly passes the file location to `uploadAvatar` and at that point there's nothing else we can do. I've also confirmed that manually uploading the avatar or curling the API works fine (see upstream issue).

If you've checked out ACLI from source, you could work around this by commenting out this line I think: https://github.com/acquia/cli/blob/fae9193756f42a2b873b573327a6747067e96b66/src/Command/CodeStudio/CodeStudioCommandTrait.php#L253

Can you please provide more details? Did this previously work and recently stop working? When? Does ACLI version affect it? Do you know if the CodeStudio GitLab version changed recently?

**Comment by joshirohit100** [comment]
Yes! This was working in past as used many time. Not sure when it started breaking.
As per https://docs.acquia.com/code-studio/release-notes/ - code studio recent version is updated to gitlab 15.8.0

Not sure if because of https://docs.gitlab.com/ee/user/admin_area/settings/account_and_limit_settings.html?_gl=1*14jg923*_ga*MTQ3NzYwNTEzOC4xNjYyNDUzMDY1*_ga_ENFH3X7M5Y*MTY3NzM5OTgwMy4xNS4wLjE2NzczOTk4NTIuMC4wLjA.#set-profiles-of-new-users-to-private-by-default?

**Comment by danepowell** [comment]
The avatar being uploaded is for the project, not the user, so I don't think the private user profile change would be relevant.

It seems likely that something else changed in GitLab 15.8.0 that broke this, and the glab client has not been updated accordingly.

**Comment by danepowell** [comment]
I opened a PR that converts this error to a warning. I doubt people will miss that avatar in the short term, and at least this allows the rest of the command to run: https://github.com/acquia/cli/pull/1384

**Comment by anavarre** [comment]
Looks like per #1384 this can be closed.
