### ISSUE TITLE
CLI-1152: drupal/date_recur issue with PHP8.1

### ISSUE THREAD

**Issue by aitala** [acquia/cli#1598]
I'm attempting to use acli to do a D7 to D9 migration but have run into an issue with the date_recur (note - this module has been an issue in a number of ways not related to acli)

I am getting this error 

```
  Problem 1
    - Root composer.json requires drupal/date_recur 3.1.0 -> satisfiable by drupal/date_recur[3.1.0].
    - drupal/date_recur 3.1.0 requires php >=7.4 <8.1 -> your php version (8.1.23) does not satisfy that requirement.
```

when doing a basic 

`acli app:new:from:drupal7 --drupal7-directory=/var/www/example.com/docroot --directory=/var/www/d9.example.com`

Any ideas?

Thanks,
Eric

**Comment by anavarre** [comment]
> your php version (8.1.23) does not satisfy that requirement.

The `date_recur` module version you're using (3.1.0) does not seem to be compatible with PHP 8.1 or above. Is it an option to upgrade the module to a newer version?

@wimleers besides for visibility and input.

**Comment by aitala** [comment]
acli puts the 3.1.0 version in composer.json and then the composer install fails.  what I did was update the json file with the 3.3RC version of date_recur, then ran composer install.

I would suggest that acli install the 3.3RC version and  3.1.0..

Eric

**Comment by anavarre** [comment]
So it looks like this might have to do with the AM:A recommendations @wimleers ?

**Comment by wimleers** [comment]
If AM:A is requiring `drupal/date_recur` in the auto-generated Drupal 9 project, then that's because the Drupal 7 source site it was pointed to had the `date_repeat` Drupal 7 module installed. (Indeed thanks to the recommendations at https://git.drupalcode.org/project/acquia_migrate/-/blob/recommendations/recommendations.json, @anavarre!)

AM:A's recommendations target Drupal 9, which requires PHP 7.4. Many but not all of its modules support PHP 8.1. And most importantly, virtually _every_ Drupal migration ever written was written during PHP 7, and few have been tested to work correctly under PHP 8.

That's why it's **strongly recommended** to run Drupal migrations using PHP 7.4 — with or without AM:A!

This is documented at:
- https://dev.acquia.com/blog/acquia-migrate-accelerate-now-open-source#faq
- https://dev.acquia.com/tutorial/drupal-7-drupal-9-hour-using-ama#switch-to-php-7.4-%E2%87%92-composer-install-+-drupal-reinstall
- https://www.drupal.org/project/acquia_migrate

<img width="642" alt="Screenshot 2024-04-12 at 2 51 06 PM" src="https://github.com/acquia/cli/assets/14240/16fec4a0-7ef7-446a-986d-29d94b31de6a">
