### ISSUE TITLE
CLI-1168: Offical docker image on dockerhub

### ISSUE THREAD

**Issue by jean-pasqualini** [acquia/cli#1607]
I'm always frustrated when I have to build my own image and the Dockerfile on the project is not suffisent especially for the file synchronisation and the ssh connect to a server host on acquia. I had to add rsync and openssh-client.

**Describe the solution you'd like**
I'd like that we create together an official image of acquia on docker hub. 

**Describe alternatives you've considered**
The alternative I've considered is to build my own image but
- it's not developer friendly
- it's not safe to use an unnoficial image

**Additional context**
I can help you do this once for all and it's not a big deal. docker hub is free when publish public images.

Plus we could build the image for different platform. I'm on the arm64 architecture and other people are on the x86_64 architecture.

**Comment by anavarre** [comment]
@jean-pasqualini Acquia CLI is mostly a wrapper for the [Cloud Platform API](https://cloudapi-docs.acquia.com/) so it's easier to use. The primary reason why we've provided a barebones Dockerfile is for Windows users who struggle with installing/managing CLI tools. We don't have on the roadmap at this time to build and maintain an image on Dockerhub.

When you invoke `api:*` endpoints, you can do most operations you'll ever need to work with the Cloud Platform. Additional commands we've added on top further simplify the workflow (e.g. `acli ide:create`). As an example, since I see you've added `rsync` and `openssh-client`, I assume you want to push/pull data to/from Cloud servers, and this can be achieved OOTB via `acli pull` or `acli push` commands already. Similarly for connecting over SSH, you don't need any library at all and can just invoke `acli remote:ssh @<SITEGROUP>.<dev|test|prod>`

**Comment by danepowell** [comment]
I think you want the Acquia image for Lando: https://docs.lando.dev/acquia/

>  I had to add rsync and openssh-client

This confused me, because on my first reading of your issue I thought you were asking to publish Acquia CLI on Dockerhub, which you could then run like `docker run -e ACLI_KEY=<key> -e ACLI_SECRET=<secret> -it acli php /usr/local/bin/acli -n <command>`.

But in that case you need rsync and SSH on your _host_ machine, not inside the container. These are pretty fundamental tools for any development environment, and I don't think shipping them in a container makes sense (at least not for their own sake). But you should be able to use them inside the Lando container.

**Comment by danepowell** [comment]
I've cleaned up the existing Acquia CLI Dockerfile and pushed an experimental version to Dockerhub: https://hub.docker.com/repository/docker/acquia/cli
