### ISSUE TITLE
CLI-1252: [New Command] To allow encrypt the text like Acquia Pipeline do

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1661]
If we need any variable to be used in pipeline which is like secure, pipeline provides way to encrypt the variable from UI and then use that same in pipeline yml file.

This issue is to add a new command to support encrypt the text/string using ACLI.

Pipeline uses API `/api/v1/ci/encrypt` (got it from the network requets from Acquia Cloud)

**Comment by danepowell** [comment]
I'm afraid we have to reject this request. Acquia already provides a Pipeline CLI with this functionality. While I'd love to see Pipeline CLI functionality integrated into Acquia CLI at some point, it would need to be done in a comprehensive way, not one ad-hoc command at a time, in order to keep the UX consistent, avoid confusion between the two tools, and ensure a stable architecture.
