### ISSUE TITLE
CLI-1265: Ability to specify port for push:database and pull:database

### ISSUE THREAD

**Issue by joelsteidl** [acquia/cli#1678]
Currently, it doesn't seem possible to specify a port for `push:database` and `pull:database`. Sometimes with Docker containers, etc specifying a non-standard DB port would be great.

For `push:database` I could hack a port in there `export ACLI_DB_HOST="127.0.0.1 --port=49575"` but `pull:database` seems more locked down.

I also tried `127.0.0.1:49575` without success.

If it's possible and I'm missing something, please let me know. Thanks!

**Comment by danepowell** [comment]
Thanks for taking the time to open an Acquia CLI issue. In order to improve your support experience and ensure issues are handled quickly and consistently, we are closing the Acquia CLI GitHub issue queue. 
- To receive priority support subject to your SLA, please visit the [Acquia Support Portal](https://acquia.my.site.com/s/) to file a ticket.
- To receive support and discuss ideas with other Acquia CLI users, please visit the newly-opened [discussions section](https://github.com/acquia/cli/discussions) on GitHub.

Rest assured, your issues will still get the same attention but with the additional benefit of Acquia's global support. Thanks for your patience during this transition.
