### ISSUE TITLE
CLI-1276: JSON format break: Notice: Composer script `post-acli-api-applications-list` does not exist in `composer.json`, skipping. This is not an error.

### ISSUE THREAD

**Issue by fiasco** [acquia/cli#1686]
**Describe the bug**
When post-acli-api-applications-list does not exist in composer.json a notice is echoed to stdout which breaks json formatting on api:applications:list calls. JQ does not seem affected by this, but attempting to decode this output in PHP fails.

**To Reproduce**
1. Use Symfony Process component to run `acli api:applications:list`
2. Pass the `getOutput` response to `json_decode` in PHP.
3. Get `null` instead of an application data object (or array).

**Comment by fiasco** [comment]
Also the case with api:applications:environment-list

**Comment by danepowell** [comment]
I'm going to need more information to reproduce this. I can run `acli api:applications:list` from any directory just fine (including ones with no composer.json, or composer.json without scripts), there's no PHP notice.

What does it mean to `Use Symfony Process component` to run the process? That doesn't sound like a supported use case.

**Comment by fiasco** [comment]
Is it possible that acli read into a local composer.json file it found? I can't reproduce this error now and I'm not exactly sure whats changed.

**Comment by danepowell** [comment]
Oh, were you running the command with verbose output? That will output additional non-JSON text. That seems like expected behavior to me. I can't imagine how you'd output "verbose" JSON. I guess we could at least print another warning saying the output won't be JSON with verbose output, so people don't think this is a bug.

For posterity: here's the code that handles Composer hooks: https://github.com/acquia/cli/blob/main/src/EventListener/ComposerScriptsListener.php

In a nutshell:

1. If you pass `--no-scripts`, nothing happens (I actually found a bug in this: https://github.com/acquia/cli/pull/1688 )
2. It looks for composer.json in your project dir, which is _generally_ the [Symfony Kernel ProjectDir](https://symfony.com/doc/current/reference/configuration/kernel.html#kernel-project-dir) but may be ACLI_REPO_ROOT if you've set that. I think we may be abusing this somewhat, since the Symfony docs talk about this being the root of a Symfony application but of course you might run ACLI in the context of a Composer-based non-Symfony app. I don't know what happens in that case.
3. If composer.json exists, you'll see verbose output indicating whether the script was found and run or not.

**Comment by danepowell** [comment]
Let me know if you need more help.
