### ISSUE TITLE
CLI-1419: acsf:sites:backup fails with Site Factory release 2.178

### ISSUE THREAD

**Issue by blairlearn** [acquia/cli#1814]
**Describe the bug**
Starting on October 17 at 05:07:06 GMT we began experiencing failures when running the `acli acsf:sites:backup SITE_ID`.

This problem happens on both production and lower tier ACSF environments.

**To Reproduce**
1. Be a user with authorization to run backups against the `MY_SITE_ID` site.
2. Run the command `acli acsf:sites:backup MY_SITE_ID`
3. See the below error:

```json
{
    "message": "Invalid JSON provided: Syntax error",
    "time": "2024-10-17T13:28:33+00:00",
    "error": 400
}
```

**Expected behavior**
I expected the output to be a JSON structure with a `taskid`, similar to:

```json
{
    "task_id": 123456
}
```

**Screenshots**

See the attached [error.txt](https://github.com/user-attachments/files/17415456/error.txt)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.7 (release v2.31.0) and Alpine 3.12 (release v2.22.2)
 - Browser n/a
 - Version v2.31.0 and v2.22.2

**Smartphone (please complete the following information):**

**Additional context**
Support ticket `01138057`

**Comment by danepowell** [comment]
Thanks for taking the time to open an Acquia CLI issue. In order to improve your support experience and ensure issues are handled quickly and consistently, we are closing the Acquia CLI GitHub issue queue. 
- To receive priority support subject to your SLA, please visit the [Acquia Support Portal](https://acquia.my.site.com/s/) to file a ticket.
- To receive support and discuss ideas with other Acquia CLI users, please visit the newly-opened [discussions section](https://github.com/acquia/cli/discussions) on GitHub.

Rest assured, your issues will still get the same attention but with the additional benefit of Acquia's global support. Thanks for your patience during this transition.
