### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Unable to write in the "cache" directory 

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#219]
Report from a user installing RC4. User is forbidden write access to `/usr/local/bin`.

```
$ mv acli /Users/myyser/Development/Acquia/

$ export PATH=/Users/myuser/Development/Acquia
$ acli auth:login

Fatal error: Uncaught RuntimeException: Unable to write in the "cache" directory (phar:///Users/myuser/Development/Acquia/acli/var/cache/prod). in phar:///Users/myuser/Development/Acquia/acli/vendor/symfony/http-kernel/Kernel.php:626
Stack trace:
#0 phar:///Users/myuser/Development/Acquia/acli/vendor/symfony/http-kernel/Kernel.php(532): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 phar:///Users/myuser/Development/Acquia/acli/vendor/symfony/http-kernel/Kernel.php(131): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 phar:///Users/myuser/Development/Acquia/acli/bin/acli(75): Symfony\Component\HttpKernel\Kernel->boot()
#3 /Users/myuser/Development/Acquia/acli(12): require('phar:///Users/g...')
#4 {main}
thrown in phar:///Users/myuser/Development/Acquia/acli/vendor/symfony/http-kernel/Kernel.php on line 626
```

**Comment by martineziortz** [comment]
Had similar error, Make sure you are running the correct version of php.

**Comment by danepowell** [comment]
@anavarre @martineziortz do you know what PHP versions cause this? Are you able to provide the output of `php -i`? I couldn't reproduce with PHP 7.2 or 7.4, the oldest and newest supported versions.

It makes sense that you'd get an error trying to write to the cache directory within the phar, since phars are read-only. But I don't understand why ACLI / Symfony is trying to write to the cache. We fully warm the cache with each release.

> User is forbidden write access to /usr/local/bin

BTW this is not a problem, just put the binary somewhere else.

**Comment by anavarre** [comment]
Unexpected, but the issue happens only with PHP 7.1

**Comment by danepowell** [comment]
Thanks, I wasn't able to confirm but I trust that PHP version was the problem.

We can't support PHP 7.1, but we can at least make it fail gracefully: #222
