### ISSUE TITLE
acli ide:php-version 7.2 leaves users in a dead end

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#224]
In IDEs, if we want `acli ide:php-version` to run for any PHP version supported in the IDE, we need to silence the PHP 7.2 error. Here's an example where switching to PHP 7.2 worked well, but upon switching to PHP 7.4 from PHP 7.2 it returned an error (but did complete the operation).

But if you try to switch to a valid PHP version, this time you'll be out of luck because you'll be on PHP 7.2 and Acquia CLI will shutdown immediately.

```
$ acli ide:php-version 7.4

Box Requirements Checker
========================

> Using PHP 7.2.31
> PHP is using the following php.ini file:
  /usr/local/php7.2/etc/cli/php.ini

> Checking Box requirements:
  E.....

                                                                                
 [ERROR] Your system is not ready to run the application.                       
                                                                                

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.3" or greater.
```

**Comment by anavarre** [comment]
Thinking more about this all I think the best course of action would be to refuse switching to PHP 7.2 and explain why, and also link to https://docs.acquia.com/dev-studio/ide/#configuring-the-php-version

**Comment by danepowell** [comment]
I agree, the best action here is for ACLI to abort if the requested version is lower than its own supported version, and link to that doc.

Incidentally, the only reason we require PHP 7.3 (I think) is because our test suite (PHPUnit 9) only supports 7.3. PHP 7.2 _probably_ works fine but we can't test or support it. Downgrading to PHPUnit 8 is probably not trivial or worth it consider that 7.2 is EOL in November.

**Comment by anavarre** [comment]
We fixed this in Cloud IDE directly!
