### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/local/bin/acli:10

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#229]
I tried installing Acquia CLI on OpenSuse. PHP 7.4 is installed with the JSON extension

```
$ php -v
PHP 7.4.9 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
$ installed php7
Loading repository data...
Reading installed packages...

S  | Name      | Summary                                              | Type
---+-----------+------------------------------------------------------+--------
i+ | php7      | Interpreter for the PHP scripting language version 7 | package
i+ | php7-json | JSON (de)serializer functions for PHP                | package
```

But `acli` refuses to bootstrap

```
$ acli
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/local/bin/acli:10
Stack trace:
#0 {main}
  thrown in /usr/local/bin/acli on line 10
```

**Comment by anavarre** [comment]
I think it might be related to the `php7-phar` extension not installed by default on Open Suse. Might be worth checking for other systems as well.

**Comment by danepowell** [comment]
It's a bit of a chicken-and-egg problem, we check for many other dependencies when running the phar (such as the json extension), but the one thing we can't check for is the phar extension itself (since you can't run the phar file in the first place).

The only easy solution is to add this to the docs.

We could also add a check to the install script, but that complicates things, since it may bind the install script to particular operating systems, and we can only guess at install time at the user's php environment. Most people will run `acli.phar` with the default CLI interpreter, but you could run it all sorts of other ways, i.e. `php7.3 build/acli.phar`.
