### ISSUE TITLE
To support different DBs in IDEs, Acquia CLI needs to create the corresponding <DB>-settings.inc file upon doing a refresh

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#242]
Take an example. Sample IDE is provisioned with sitegroup "test". Automatically, the configuration overrides in the IDE will be stored under `/var/www/site-php/test/test-settings.inc`

But upon selecting a different database than the default one via Acquia CLI, then the expected path might become `/var/www/site-php/test/db2-settings.inc`

But the IDE in question won't be updated accordingly. This leaves the user in a dead end because the configuration overrides AND DB credentials are not preconfigured for this specific sitegroup's database.

What we should do is upon doing an `acli refresh` AND selecting a DB, rename `/var/www/site-php/<SITEGROUP>/<DB>-settings.inc` so `DB-settings.inc` is modified accordingly to the database name we're pulling.

**Comment by danepowell** [comment]
It pains me that this is the best solution because it feels like such a hack, but I can't think of a better alternative. We've hit the limit of our "IDEs should behave like any other environment" paradigm, because other environments are tied to hardware (each with its own filesystem), while IDEs need to work across all sites/environments/applications on a subscription regardless of the underlying hardware/filesystem.

For reference, the reason this isn't an issue in other environment types is because Pipelines doesn't even manage settings, and CDEs force you to select up to 3 databases _a priori_ to host in the containers.

We'd want to copy (not rename) the files since there's some duplication and different application code may include them differently (for instance, [ACSF's include is specific to Drupal version](https://github.com/acquia/acsf/blob/2.106.0.3886+20200723+d8/acsf_init/lib/sites/g/settings.php#L107), while [BLT's is not](https://github.com/acquia/blt/blob/12.2.0/settings/blt.settings.php#L102))

**Comment by anavarre** [comment]
> We'd want to copy (not rename) the files since there's some duplication and different application code may include them differently (for instance, ACSF's include is specific to Drupal version, while BLT's is not)

Initially I wondered about adding as many `<DB>-settings.inc` files as detected within the sitegroup upon provisioning the IDE but quickly realized this wouldn't take into account the use case when a new DB (or, site) would be created after the fact.

Also agreed creating a new file is likely best, and certainly won't hurt.

**Comment by danepowell** [comment]
On second thought, I think this can and should be solved in IDEs.

ACSF sites use data from a global variable to determine which db-specific settings file to include: https://github.com/acquia/acsf/blob/2.106.0.3886+20200723+d8/acsf_init/lib/sites/g/settings.php#L101

That global info ultimately comes from a `sites.json` file that's ubiquitous on ACSF, we'll probably want that in Cloud IDEs regardless: https://github.com/acquia/acsf/blob/5448c6ca74c0c1cabbad721947b59646637ca8a7/acsf_init/lib/sites/g/sites.inc#L237

IDEs should set the db name in `sites.json` to a static value corresponding to the settings file names.

**Comment by anavarre** [comment]
> IDEs should set the db name in sites.json to a static value corresponding to the settings file names.

This only applies to ACSF. We do have many multisites on ACE, too.

cc/ @joazvsoares

**Comment by danepowell** [comment]
I still don't like the idea of copying and renaming files.

Acquia's docs don't provide much guidance on how to handle settings includes for multisites: https://docs.acquia.com/cloud-platform/manage/code/require-line/

The only "standard" method of handling multisite settings is via BLT, and I'd rather change the BLT code to accommodate IDEs than to hack the settings files via ACLI.

If everyone else agrees, then we'd want to close this and open tickets for IDEs and BLT.

**Comment by grasmash** [comment]
> I still don't like the idea of copying and renaming files.

I agree.

**Comment by anavarre** [comment]
Ok, let's step back and explore our options:

* Either we detect all existing databases when creating the IDE, and create as many files under `/var/www/site-php`
  * This means DBs created after the IDE creation will fail to be synchronized.
  * We know from discussions with customers they usually tend to never delete their IDE after it's been created (especially if setting it up was painful to start with)
  * This means we don't have a great solution, but a solution nonetheless that should account for the 80% or more
  * This is all depending on being able to retrieve all existing DBs for a sitegroup via the Cloud Platform API
* Or, we use `acli` to `cp /var/www/site-php/SITEGROUP/DBNAME-settings.inc cp /var/www/site-php/SITEGROUP/NEWDBNAME-settings.inc` on an ad-hoc basis.

The latter seems very easy to do in comparison.

**Comment by danepowell** [comment]
I was about to make the argument that if you're using db-specific includes, "you're doing it wrong!!", but I'll relent :smile: Pragmatically, I think copying the settings file on refresh is going to lead to the least customer pain, so let's do it.

I was _going_ to ask what codebase you're using that's importing `/var/www/site-php/SITEGROUP/DBNAME-settings.inc`? And how/why did you create the codebase that way? Because I can't find any public documentation/recommendation that anyone should be using those db-specific settings files. They seem like a hidden / private API, and therefore not something we want to officially support.

But even without waiting for an answer, I can assume that regardless of how/why, customers probably _are_ using them and therefore we should at least attempt to support them in IDEs.

(Incidentally, in examining those settings files, there's only a single line that's different between the file for each database: `$databases['default']['default'] = 'foo'`. Presumably, the way this is supposed to work is that you only include the master db settings file, and then set `$databases['default']['default'] yourself in settings.php. But since this isn't actually documented anywhere, I don't want to assume that everyone actually does it that way)

**Comment by anavarre** [comment]
> I was going to ask what codebase you're using that's importing /var/www/site-php/SITEGROUP/DBNAME-settings.inc? And how/why did you create the codebase that way? Because I can't find any public documentation/recommendation that anyone should be using those db-specific settings files. They seem like a hidden / private API, and therefore not something we want to officially support.

This is expected for all Acquia applications, and something you can find with the require line:

```
if (file_exists('/var/www/site-php')) {
  require '/var/www/site-php/SITEGROUP/DBNAME-settings.inc';
}
```

So in other words this means when you create a new DB on the Cloud Platform, then you have a new require line that is generated and keeps the same sitegroup, but changes the DB name for obvious reasons.

In IDEs, we just ensured we'd have the same file available so we'd apply our own configuration overrides. This is how we define the DB connection:

```
$databases['default']['default'] = [
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'host' => 'localhost',
  'port' => '3306',
  'driver' => 'mysql',
  'prefix' => '',
];
```

> Presumably, one way this could work is to only include the master db settings file, and then set $databases['default']['default'] yourself in settings.php.

The idea with Cloud IDE is upon refreshing any arbitrary DB (since it's a thing now) you'd get the DB connection automatically configured as it's the case today for the `default` DB.

> it begs the question of why the multiple files exist in the first place.

That's a question for the Cloud Platform since 2007 :smile:
