### ISSUE TITLE
Missing access token causes lengthy API calls

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#297]
Every time I run an API call such as `acli api:environments:database-list <uuid>`, it takes 4-5 seconds, whereas hitting the API directly takes only 1 second.

The root cause seems to be the typhonius sdk generating a new access token for every API call, because the access token field is empty: https://github.com/typhonius/acquia-php-sdk-v2/blob/9321b5fb4f9509447fcfd95a9490f8d839ca9b9b/src/Connector/Connector.php#L60

**Comment by eporama** [comment]
I am not sure that it does… I profiled a request with xhprof to track `./bin/acli api:environments:database-list <app>.<env>` and got 5 `curl_exec` requests. One to amplitude, one for the oauth token and then one each for `Acquia\Cli\Command\CommandBase::getApplicationFromAlias`, `AcquiaCloudApi\Endpoints\Environments::getAll`, and `Acquia\Cli\Command\Api\ApiCommandBase::execute`.

This all makes sense and doesn't seem to jibe with requesting new tokens. Each `curl_exec`, however, was in the 4 second range, so I'm curious what might be causing that slowness.

**Comment by danepowell** [comment]
My evidence is based on xdebug, I saw the createRequest() method being called every time and taking ~4 seconds, with the accessToken member being NULL.

**Comment by typhonius** [comment]
I just stumbled on this thread and wanted to add my own empirical evidence. I added in some basic debugging statements for both my original acquia_cli tool and acli and found that the access token was being created only once regardless of how many chained requests were being made.

e.g. To get a list of db backups

- Query /applications endpoint to get a application UUID
- Query /applications/<uuid>/environments endpoint to get environment UUID
- Query /applications/<uuid>/databases endpoint to get all application DBs
- Query all of the DB backups endpoints (in my case I had 4 DBs so * 4)


```
➜  acquia-cli git:(github-actions) ✗ ./bin/acquiacli db:backup:list devcloud:deloittedigital prod
int(1602370739)
string(38) "creating request: get => /applications"
string(20) "access token is: ..."
string(13) "getting token"
int(1602370745)
string(88) "creating request: get => /applications/99c0af92.../environments"
string(26) "access token is: eyJ0eX..."
int(1602370748)
string(85) "creating request: get => /applications/99c0af92.../databases"
string(26) "access token is: eyJ0eX..."
int(1602370749)
string(116) "creating request: get => /environments/238869.../databases/deloittedigital/backups"
string(26) "access token is: eyJ0eX..."
int(1602370750)
string(107) "creating request: get => /environments/238869.../databases/foobar/backups"
string(26) "access token is: eyJ0eX..."
int(1602370752)
string(111) "creating request: get => /environments/238869.../databases/my_newDb_2/backups"
string(26) "access token is: eyJ0eX..."
int(1602370753)
string(105) "creating request: get => /environments/238869.../databases/saml/backups"
string(26) "access token is: eyJ0eX..."
```

Looking at this, it appears the access token is only requested once (at the beginning) and all of the subsequent requests are taking around a second to come back.

I remember that we added in the check for token expiry because long running commands using the cli tool (downloads of enormous db backups) were surpassing the 5m token lifetime and causing errors. We unfortunately can't use refresh token functionality because it's not implemented on the server end (or at least it wasn't when we tried).

- https://github.com/typhonius/acquia-php-sdk-v2/issues/48#issuecomment-586505250
- https://github.com/typhonius/acquia-php-sdk-v2/pull/49

**Comment by typhonius** [comment]
I see that you've included some caching functionality for site and environment UUIDs. It might be possible to cache the access token as well -- I could add in a setAccessToken method (or something) for external libraries who manage access tokens in this way to allow easy reuse of tokens.

If Acquia has implemented refresh token functionality on the API then this could be converted into a really robust solution as the league OAuth library states that you should be able to use an old access token to make a refresh token request.

**Comment by grasmash** [comment]
@itafroma do you know if the refresh token has been implemented yet?

**Comment by itafroma** [comment]
We have no plans to support refresh token for customers using the client credentials flow: the refresh token is only needed when the client does not have access to the user's username and password, or their API token and secret. Customers have access to the latter.

You should be caching the access token: it only expires after 5 minutes.

**Comment by typhonius** [comment]
I suppose a question to this group would be whether extending libraries would implement access token caching or whether the SDK would. I can see pros/cons to both but wanted to canvas additional views before starting anything. Main pro for implementing in the SDK is to keep all authentication in there and being much simpler to write, with the only con being that it would increase the size/dependencies of the library.

**Comment by typhonius** [comment]
POC over here for adding it to the SDK: https://github.com/typhonius/acquia-php-sdk-v2/pull/92

**Comment by grasmash** [comment]
I would personally prefer to keep it in the SDK. I try to rely on that for all of the logic related to actually making requests to the API.

**Comment by typhonius** [comment]
I'm pretty happy to merge the above PR into the SDK. I've tested the branch on Acquia_Cli and it all works just fine. More for my peace of mind than anything, could I ask you to test it on acquia/cli to ensure it doesn't break anything before I merge?

**Comment by typhonius** [comment]
One other consideration I’ll need to think about is the implications of storing an access token in temp. Especially if that makes it available to other users of the system - however unlikely that may be...

**Comment by grasmash** [comment]
I've done some quick testing of the `add-cache` branch and it seems to be working fine.

Tested `ide:list`, `ssh`, asd `sa`.

**Comment by typhonius** [comment]
Thanks, it’s been added. I switched the cache directory to be within the user’s home (At .acquia-php-sdk-v2) because my testing on mac/Linux revealed cache items were readable by other users. 

I’m not opposed to switching to the .acquia location but figured that’s not the library’s namespace (plus it’s a 5m cache so wouldn’t be breaking if we changed it later).

**Comment by grasmash** [comment]
Resolved by https://github.com/acquia/cli/pull/321
