### ISSUE TITLE
acli remote:drush behaving differently than drush for certain scenarios

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#341]
We're attempting to use remote:drush, but we're seeing some weird/specific issues, perhaps you may have a clue. We use [Rundeck](https://www.rundeck.com/open-source) for some scripts automation, and we setup jobs to run certain drush scripts, for clearing caches, user-login and etc.

We setup a bash script to run those drush scripts via rundeck, which have its own magic to deal with theses bash scripts execution. The point, when I run `acli remote:drush` I have different behavior from running `drush`.

For example, below is inside a bash script (uses acquia aliases):

```
drush @site.dev cache-rebuild || exit 1 
```

If it succeeds, it continues the execution of the bash script, when it fails (if site is somehow broken, or alias is invalid, etc), it ends the execution with the `exit 1`.

At the same time, if I run same thing via acli, the bash script execution hangs in that exact line (ultimately timing out the rundeck job), no matter if it remote drush response succeeds or fail  (the drush command itself runs via acli, but rundeck bash script handler never retrieve the acli remote drush exit status code, afaict).

```
acli remote:drush -- @site.dev cache-rebuild || exit 1 
```

Also, want to bring this happens only in the rundeck bash script wrapper, if I run locally in my terminal, it works perfectly fine, while regular drush works fine both locally and in the rundeck service.

I am not sure what's going on, but if you have any idea on that would be super since it's happening only with acli, while drush works fine.

**Comment by anavarre** [comment]
Oops, sorry for the delay in responding here, Leo. @danepowell would you have any idea what is happening here?

**Comment by danepowell** [comment]
I cannot reproduce this, though I'm not familiar with Rundeck and haven't tested it there. But I put the following command in various forms of Bash scripts and it returned as expected: `acli remote:drush -- @site.dev asdf || echo $?` (failing as expected since asdf is not a Drush command)

Are you sure Rundeck is using Bash and not some other shell? Are you sure you are authenticated to Cloud in Rundeck? Probably the answer to both is yes, but it's worth checking.

Can you post the output of the command with `-vvv`? Do you get any output at all?

Finally, is it possible that Rundeck is doing something funky with TTY, maybe running the command in a non-interactive shell, or with different SSH options, that would explain why it works when you run the command manually but not via Rundeck?

If none of those provide a clue, you'll probably need to start breaking down the command (i.e. remove the pipe, or pipe it to something that will provide more debugging information) to see where the problem is.
