### ISSUE TITLE
Acquia CLI should bail immediately when required PHP extensions are missing

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#343]
See https://docs.acquia.com/acquia-cli/install/#requirements - It seems like we should check for 2 extensions:

* https://www.php.net/manual/en/book.json.php
* https://www.php.net/manual/en/book.phar.php

**Comment by danepowell** [comment]
It already does, if PHP extensions or versions are incompatible: https://github.com/box-project/box/blob/master/doc/requirement-checker.md

The only exception is if the Phar extension is missing, there's literally nothing we can do about that since you wouldn't be able to bootstrap the ACLI phar file in the first place.
