### ISSUE TITLE
Codebase workflow re Git and Cloud Platform - poss Noob question!

### ISSUE THREAD

**Issue by SamFoster** [acquia/cli#521]
Guys 

Please forgive me if this is a stupid question...and relates mainly to the creation of an entirely new site and its 'publication' onto the cloud platform once it has been initially created in the IDE. (I can see a working site in the IDE - but can't see how it should be successfully 'published' to my cloud application)

I've watched the overview video Dane produced, I walked thru the docs on Acquia etc but I'm a little stumped re the workflow for the codebase.

I have an IDE created, and I have used the wizard to create a new Drupal site in the IDE using the 'recommended-project' and thence I have run through the installation of the site.

I can see that in the IDE I can run cmds to push the db and the files 

It's the code I am confused about. Am I supposed to configure Git in the IDE to connect it to the Acquia GIT repo using the Git url I would get from within the Cloud Platform? Explanation of that step is missing from any docs if so. I had a thought that I had screwed stuff up, so I restarted the whole setup process again, but I see having done so that the IDE has no remotes configured. Is there a page somewhere I should have read (RTFM!). I presume you also need to add an SSH key etc too?

Is there any part of that connection to the Aquia cloud git repo that is automatically done if you choose a certain wizard? I guess it would be if I had chosen to download the application from something already setuo and functioning in the cloud platform. In my case however I am creating a new site, in a new, (virgin) cloud application.

If one connects the remote to the Git repo for the cloud platform xxxxx@svn-xxxxx.prod.hosting.acquia.com:xxxxx.git  can one additionally connect to a second Git remote - or is that not really expected behaviour (of the users)?

Whilst I am asking this can I ask if there are any docs concerned with creating a multi-site setup with acli? I can see one comment in the faq, but once I get over the basics of using this to deploy the codebase etc that'll be my next hurdle!

Thanks

Sam

Thanks in advance.

**Comment by SamFoster** [comment]
Guys

Any chance of a little nudge in right direction here

If you use the 'Getting Started' wizard to create a new site - which effectively just kicks off 'acli new /home/ide/project' do you then have to manually connect your IDE to the GIT repo which sits behind your cloud application?

Thanks

Sam

**Comment by anavarre** [comment]
@SamFoster sorry for the delay and thanks for asking!

At a high level, it's easier to pull your app into the IDE than it is to do it the other way around. Focusing on the code portion you mentioned you are struggling with, your confusion makes sense because there's a little bit of work required and I'll try to explain why:

* When you clone your code from the Cloud Platform into the IDE, you get the Acquia base repository which contains your Git history. Any change you make is just a `git commit` and `git push` away.
* On the contrary, when you create an entirely new app in the IDE we don't have any knowledge of your Acquia Git repository and can't auto-magically plug it in.
* So we have to do this little dance which consists of either:
  *  [EITHER] Cloning the code, renaming the `project` directory to e.g. `project1`, then creating a new `project` directory and creating the new app under it, deleting its `.git` directory, then moving the "right" `.git` directory from `project1` to `project` and then wiping `project1` altogether so only `project` remains with the `.git` directory and the new code to push to your Acquia Git repository.
  * [OR] Creating your app (which I understand you did), wiping your `.git` directory, then renaming `project` to `project1`, creating a new `project` directory to clone the app, then moving your `.git` directory from `project` to `project1`, then wiping `project` entirely, then renaming `project1` to `project`.

It might looks crazy complicated when you read it, but when you do you'll see it's just a few commands.

> Explanation of that step is missing from any docs if so.

Point taken. @grasmash and @danepowell any way you can think of we could streamline this with ACLI?

> I presume you also need to add an SSH key etc too?

No matter what you done (existing app or new app) you need to configure your IDE so that you're a) authenticated against the Cloud Platform API and b) have generated an uploaded an SSH key to your Cloud Platform account. All of this should be very easy to do when you click on the "Configure IDE" button from the "Get Started" page.

> If one connects the remote to the Git repo for the cloud platform xxxxx@svn-xxxxx.prod.hosting.acquia.com:xxxxx.git can one additionally connect to a second Git remote - or is that not really expected behaviour (of the users)?

You are free to have as many Git remotes as you'd like. It's something built-in Git. It's unrelated to Cloud IDE or Cloud Platform.

> Whilst I am asking this can I ask if there are any docs concerned with creating a multi-site setup with acli? I can see one comment in the faq, but once I get over the basics of using this to deploy the codebase etc that'll be my next hurdle!

This is no longer ACLI business to deal with multi-site. That's purely Drupal. I'd recommend you start here: https://www.drupal.org/docs/multisite-drupal

**Comment by SamFoster** [comment]
Thanks for the response man - I'm digesting that all now 

I did also notice that my GIT cmd line commands worked - but the IDE 'click to push/pull' type things were giving me errors - But I've held back on reporting those until I had established it wasn't me being stupid!

I'll get back to you on this in a bit - and also try the updated PHAR re the Windows browser issue 'not opening' issue/fix

Thanks

Sam

**Comment by SamFoster** [comment]
@anavarre 

VERY helpful response - I thought I'd been going slowly mad - I will try the setup 'dance' in a bit.

I had successfully done all the SSH stuff anyway having run the command which has it's shortcut in the 'getting started' tab/page

re mutlisite - fair enough - I just wondered if there was some magic available - and that made it as easy as was in DEV Desktop. But understand it's out of ACLI dev scope etc

Thanks again!

Sam (form a sunny North Wales, UK)

**Comment by anavarre** [comment]
Good luck, Sam, and enjoy the sunny day!
