### ISSUE TITLE
Creating an IDE downloads Acquia CLI 1.9.0 with no way to update

### ISSUE THREAD

**Issue by nmangold** [acquia/cli#549]
When creating a new IDE, version 1.9.0 is used in the IDE. Within the IDE, when `acli pull`, or any other command runs that tries to update itself, including `acli self`, the following error is encountered.

```
Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: HTTP request failed! HTTP/1.1 403 rate limit exceeded
 in phar:///opt/local/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70
```

**Comment by anavarre** [comment]
This is a known issue that was fixed in Acquia CLI 1.11.0 via #519 

The TL;DR is Cloud IDE is being seen from the outside world with the same IP address, and when too many API calls are being made to the GitHub API, we are running into API limits. In other words, what failed for you before might very well work today without any issue so I'd suggest you try again.

We are going to release a new version of Cloud IDE this week which will ship with Acquia CLI 1.11.0 so you don't run into the issue again. Please watch https://docs.acquia.com/ide/release-notes/
