### ISSUE TITLE
CLI-657: Check whether the user role has permissions to SSH into a non production environment and fail gracefully if not

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#818]
Cloud IDE users can run into the following issue:

<img width="869" alt="Screen Shot 2022-02-17 at 08 53 25" src="https://user-images.githubusercontent.com/293478/154430492-bf57873e-0e22-41a0-9cd4-53e1ae2fef61.png">

This is due to roles (e.g. [Developer role by default](https://docs.acquia.com/cloud-platform/access/teams/permissions/default/)) not having permissions to create SSH keys.

Instead of just timing out, we should first perform a permissions check and fail gracefully with instructions.

**Comment by grasmash** [comment]
Are you sure about this? Before we poll Acquia cloud and wait 15 minutes, we do try to upload the key by POSTing it to `/account/ssh-keys`. If that returns anything but a 202, we throw an exception: https://github.com/acquia/cli/blob/master/src/Command/Ssh/SshKeyCommandBase.php#L457

**Comment by anavarre** [comment]
I just now a user report indicated this and the fix was with missing permissions for the Developer role. What you indicate would seem to take care of this though, right?

**Comment by grasmash** [comment]
Cloud API should return an error indicating the lack of permission.

**Comment by danepowell** [comment]
I think we're conflating a few issues here. Team permissions have nothing to do with the ability of a user to upload an SSH key; that should always succeed regardless of permissions. The "manage SSH keys" permission that's unavailable to developer roles _sounds_ like it would affect that, but in fact that permission does literally nothing (CXAPI-9443).

The issue here is that we poll a dev environment and developers lack the "[Add SSH key](https://docs.acquia.com/cloud-platform/manage/ssh/enable/add-key/#ssh-using-key) to non-production environments" permission

**Comment by grasmash** [comment]
Ah! now that makes sense. They do have permission to create and upload the key, but they don’t have permission to SSH into an environment.
